# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseworkNo', models.CharField(max_length=10)),
                ('CourseworkTitle', models.CharField(max_length=50)),
                ('AssessmentType', models.CharField(max_length=50)),
                ('IssueDate', models.DateField()),
                ('DueDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleMark', models.IntegerField()),
                ('SubmittedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleCode', models.CharField(max_length=10)),
                ('ModuleTitle', models.CharField(max_length=40)),
                ('ModuleTutor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('StudentFirstName', models.CharField(max_length=20)),
                ('StudentLastName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Postcode', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='modulemarks',
            name='ModuleCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Modules'),
        ),
        migrations.AddField(
            model_name='modulemarks',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Student'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='ModuleCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Modules'),
        ),
    ]
